sudo: required
services:
  - docker

before_install:
  - docker build -t agencyzero/react-dev-test -f ./client/Dockerfile.dev ./client

script:
  - docker run agencyzero/react-dev-test npm test -- --coverage

after_success:
  - docker build -t agencyzero/multi-client ./client
  - docker build -t agencyzero/multi-nginx ./nginx
  - docker build -t agencyzero/multi-server ./server
  - docker build -t agencyzero/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push agencyzero/multi-client
  - docker push agencyzero/multi-nginx
  - docker push agencyzero/multi-server
  - docker push agencyzero/multi-worker
